package com.very.card.dao;

import org.springframework.stereotype.Repository;

import com.very.card.model.Introduction;
@Repository
public interface IntroductionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table introduction
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table introduction
     *
     * @mbggenerated
     */
    int insert(Introduction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table introduction
     *
     * @mbggenerated
     */
    int insertSelective(Introduction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table introduction
     *
     * @mbggenerated
     */
    Introduction selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table introduction
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Introduction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table introduction
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Introduction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table introduction
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Introduction record);
}