package com.very.campaign.dao;

import com.very.campaign.model.Campaign;

public interface CampaignMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campaign
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campaign
     *
     * @mbggenerated
     */
    int insert(Campaign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campaign
     *
     * @mbggenerated
     */
    int insertSelective(Campaign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campaign
     *
     * @mbggenerated
     */
    Campaign selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campaign
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Campaign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campaign
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Campaign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campaign
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Campaign record);
}